FROM nginx:alpine
COPY staging/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY staging/docker-entrypoint.sh /docker-entrypoint-amqur.sh
COPY staging/public/ /usr/share/nginx/html/
RUN chmod +x /docker-entrypoint-amqur.sh \
  && rm -f /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["/docker-entrypoint-amqur.sh"]
